name: cels
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - seaborn=0.13.2
  - scikit-learn=1.5.0
  - pyts=0.12.0
  - opencv=4.7.0
  - pillow=10.4.0
  - scipy=1.10.0
  - pip
  - pip:
      - wandb==0.16.6
      - shortuuid==1.0.13
      - fastdtw==0.3.4
